### ISSUE TITLE
"Start by typing" hint overrides text in lixt

### ISSUE THREAD

**Issue by alexmik89** [Ramotion/reel-search#11]
1. Tap on Start to Typing
2. Tap on on cross to remove text
3. Hint Start by typing will be shown and overrides text in list
   ![img_0648](https://cloud.githubusercontent.com/assets/9883651/19684056/d7fc7ce6-9abd-11e6-8272-d0c3136821f6.PNG)

**Comment by jaymathew** [comment]
I am having the same problem, have you found a fix for this?   I would love to use this in my app, but this bug is a show stopper for me.

**Comment by mcutchember** [comment]
Still no fix?

**Comment by mattvb91** [comment]
Anyone able to fix it? Along with https://github.com/Ramotion/reel-search/issues/12 this is unusable.

This repo seems dead. Anyone have an active fork?

**Comment by RamotionRussell** [comment]
f9f7c5c11cdd876e59eef3f053828db3a9d73033
