### ISSUE TITLE
Case-insensitive  input matching?

### ISSUE THREAD

**Issue by Lwdthe1** [Ramotion/reel-search#14]
I can't seem to figure out how to do case-insensitive input matching. By this, I mean I would like a input of "michael" to show all possible inputs like "Michael". This doesn't have to be added now. I'd at least like to know where is best to make that change.

**Comment by Skogetroll** [comment]
Just define your own type, conforming to [`FlowDataSource`](https://rawgit.com/Ramotion/reel-search/master/docs/Protocols/FlowDataSource.html), and init `RAMReel` with instance of that type.

**Comment by RamotionRussell** [comment]
The new trie implementation (since 88a1da7b81edac564aafccf16ca3aaffca175fd4) example uses case-insensitive matching, but do be aware that this causes a visual clash between letter cases, since the typed text and suggestions are displayed on top of each other.

**Comment by aheze** [comment]
Hello, I'm wondering if there is a fix for the "visual clash"? Besides maybe hiding the collection view when the user enters a capital letter, has there been any development on the issue? Is there a way to adjust the datasource to match the case that the user-entered text is in?
