### ISSUE TITLE
Fatal Error: Index out of range

### ISSUE THREAD

**Issue by kalidosstesark** [Ramotion/reel-search#15]
Hi Team, 

  I got Fatal Error: 

RAMReelExample[6907:71424] [MC] Reading from private effective user settings.
fatal error: Index out of range

![screen shot 2017-03-13 at 12 26 17 pm](https://cloud.githubusercontent.com/assets/24803874/23844456/57996b16-07e8-11e7-9d5b-7c9e54b68e56.png)

**Comment by RamotionRussell** [comment]
88a1da7b81edac564aafccf16ca3aaffca175fd4
