### ISSUE TITLE
Tap textField to select (like in the gif) ?

### ISSUE THREAD

**Issue by andres-cianio** [Ramotion/reel-search#17]
I love this component, sleek and works awesome; but there is something I don't think is working.
In the gif, the user can scroll the collection and tap the textField, so the option shown behind it is selected.
It seems at the moment this is not working, so there is no easy way to select the option shown behind the textfield. Furthermore, when I tap done in the keyboard, I only get the textField content; whereas I would expect to get the option that is being "suggested".
Is there anyway this functionality might be included again? Or maybe I'm missing the point of the component ;p

**Comment by andres-cianio** [comment]
I just realized, no matter where I tap, the option behind the textfield is selected... Don't know if it is the intended way to work, but it's good enough for me.

**Comment by emirbeytekin** [comment]
> Furthermore, when I tap done in the keyboard, I only get the textField content; whereas I would expect to get the option that is being "suggested".

Definitely should have this feature.

**Comment by emirbeytekin** [comment]
> I just realized, no matter where I tap, the option behind the textfield is selected... Don't know if it is the intended way to work, but it's good enough for me.

this misleads users, they want to choose what they touched on
