### ISSUE TITLE
Doesn't work with swift 4.1 on xcode

### ISSUE THREAD

**Issue by tnishida1** [Ramotion/reel-search#26]
I've been trying to get this plugin in, as well as your one here:
https://github.com/Ramotion/animated-tab-bar

I'm running on Xcode 9.4.1, using Swift 4.1 for my project, and using IOS 11.4.
I tried to pull your project here and I get a bunch of compile errors when I try to build the project.
I can put screencaps of the errors I'm getting if necessary.
Any help is greatly appreciated!

**Comment by quintus-luis** [comment]
Same problem here!

**Comment by josteph** [comment]
Swift 4.2 support please.
