### ISSUE TITLE
Actions when something from the list is selected.

### ISSUE THREAD

**Issue by Dershowitz011** [Ramotion/reel-search#7]
Could you update the readme which can tell how to add an action when u select something in the list? Thanks!

**Comment by Skogetroll** [comment]
[Done](https://github.com/Ramotion/reel-search/releases/tag/1.2.4).

**Comment by Dershowitz011** [comment]
Hey could you please check this out too? [Actions to do once the walkthrough is over](https://github.com/Ramotion/paper-onboarding/issues/8). Been trying to ask but nobody is helping. Thanks!
